[ 방정식, 미적분, 합성곱 알아보기 ]

In [2]:
import numpy as np

In [4]:
ef = np.array([1,-2,1])
p = np.poly1d(ef)
p

poly1d([ 1, -2,  1])

In [5]:
print(p)

   2
1 x - 2 x + 1


In [6]:
type(p)

numpy.poly1d

In [7]:
# 다항식의 미지수인 변수를 variable속성으로 확인
# 현재 만들어진 다항식의 차수를 order속성으로 확인
print(p.variable)
print(p.order)

x
2


In [8]:
# 다항수의 계수는 coef, coefficients, coeffs 속성으로 확인
p.coef

array([ 1, -2,  1])

In [9]:
p.coefficients

array([ 1, -2,  1])

In [10]:
p.coeffs

array([ 1, -2,  1])

In [11]:
# 방정식의 해(roots)
p.roots

array([1.+6.68896751e-09j, 1.-6.68896751e-09j])

In [12]:
# 다항식 객체에 0을 인자로 전달해서 방정식의 해를 구할 수 있음
p[0]

1

In [13]:
np.roots(ef)

array([1.+6.68896751e-09j, 1.-6.68896751e-09j])

[ 차분과 미분과 적분 ]

In [14]:
x = np.array([1,2,4,7,10])
np.diff(x)

array([1, 2, 3, 3])

In [15]:
for i in range(len(x)-1):
    print(x[i+1]-x[i])

1
2
3
3


In [16]:
np.diff(x, n=2)

array([1, 1, 0])

In [17]:
c = np.diff(x)
np.diff(c)

array([1, 1, 0])

In [18]:
x = np.array([1,2,3,4,5,6])
dx= np.diff(x)
dx

array([1, 1, 1, 1, 1])

In [19]:
y = np.array([2,4,6,8,10,12])
dy = np.diff(y)
dy

array([2, 2, 2, 2, 2])

In [23]:
dydx = np.zeros(y.shape,float)
dydx

array([0., 0., 0., 0., 0., 0.])

In [24]:
dydx[:-1] = dy/dx
dydx

array([2., 2., 2., 2., 2., 0.])

In [25]:
dydx[-1] = (y[-1]-y[-2])/(x[-1]-x[-2])
dydx

array([2., 2., 2., 2., 2., 2.])

In [26]:
np.gradient(y)

array([2., 2., 2., 2., 2., 2.])