[ 3-4. 메소드나 함수로 검색하기 ]

In [1]:
import numpy as np

In [5]:
x = np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [6]:
np.choose(0,x)

array([0, 1, 2])

In [7]:
np.choose([0],x)

array([0, 1, 2])

In [ ]:
# 인덱스범위가 벗어난 것을 조회할 떄는 예외 발생
try:
    np.choose(3,x)
except Exception as e:
    print(e)

invalid entry in choice array


In [9]:
tuple([0,1,2])

(0, 1, 2)

In [10]:
np.choose(tuple([0,1,2]),x)

array([0, 4, 8])

In [ ]:
np.choose(tuple([2,1,0]),x) # indices 배열이 내림차순 ([2,1,0])이면 결과도 반대로 나옴

array([6, 4, 2])

In [ ]:
np.where(x>4) # 행과 열의 인덱스 정보를 반환

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [ ]:
x[np.where(x>4)] # 논리값의 결과를 색인연산에 넣어서 원소를 반환

array([5, 6, 7, 8])

In [14]:
x>5

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True]])

In [16]:
np.select(x>5,x)

array([6, 7, 8])

In [ ]:
a = np.select(x>5,x*2) # select함수는 선택되는 배열도 특정상태 변경 가능
print(a)

[12 14 16]


In [19]:
# 단순하게 특정 조건에 따른 원소 추출 -> extract
np.extract(x>4,x)

array([5, 6, 7, 8])

[ 4-1. 산술연산 ]

In [20]:
d = np.array([3,4])
e = np.array([5,6])

In [21]:
np.add(d,e)

array([ 8, 10])

In [ ]:
f = np.array([1,2,3])

try:
    f+e
except Exception as ex:
    print(ex)
    
# 다른 백터 공간에 있는 벡터는 연산 할 수 없음

operands could not be broadcast together with shapes (3,) (2,) 


In [24]:
d - e 

array([-2, -2])

In [26]:
np.subtract(d,e)

array([-2, -2])

In [27]:
d + (-e)

array([-2, -2])

In [ ]:
# 두번쨰 벡터의 반대방향을 표기하고 이를 더하는 방식의 방식이 벡터간의 뺄셈
np.add(d, np.negative(e))

array([-2, -2])

In [29]:
d= np.array([2,3])

In [30]:
3 *d

array([6, 9])

In [31]:
np.array([3,3]) * d

array([6, 9])

In [33]:
# multiply
np.multiply(3,d)

array([6, 9])

In [34]:
np.multiply(np.array([3,3]),d)

array([6, 9])

In [35]:
1/3 *d

array([0.66666667, 1.        ])

In [36]:
np.divide(d,3)

array([0.66666667, 1.        ])

In [38]:
np.multiply(d,(1/3))

array([0.66666667, 1.        ])

[ 4-2 브로드캐스팅 ]

In [ ]:
x1 = np.ones(3) # 단순히 길이가 3인 1차원 배열을 생성
print(x1)

[1. 1. 1.]


In [ ]:
x1.shape # 그래서 결과가 (1,3)이 아니라 (3,)으로 나옴

(3,)

In [41]:
# newaxis으로 행 차원을 추가할 수 있음
x1 = x1[np.newaxis,]

In [43]:
x1.shape

(1, 3)

In [44]:
# 행렬 dot prodouct 계산 : 행렬분해이용
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
b = np.array([[1,2,3], [4,5,6], [7,8,9]])

np.dot(a,b)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [45]:
c = b[:,0] # columns[0]을 추출
d = b[:,1] # columns[1]을 추출
e = b[:,2] # columns[2]을 추출

In [ ]:
# 아래 행렬의 1차원 행렬
print('c:',c)
print('d:',d)
print('e:',e)

c: [1 4 7]
d: [2 5 8]
e: [3 6 9]


In [48]:
# 열을 추가하여 2차원으로 만들기
c = c[:, np.newaxis] 
d = d[:, np.newaxis]
e = e[:, np.newaxis]

In [51]:
print('c:',c)
print('d:',d)
print('e:',e)

c: [[1]
 [4]
 [7]]
d: [[2]
 [5]
 [8]]
e: [[3]
 [6]
 [9]]


In [52]:
# dot product 연산 후에 하나로 통합
f = a@c
g = a@d
h = a@e
print('f:',f)
print('g:',g)
print('h:',h)

f: [[ 30]
 [ 66]
 [102]]
g: [[ 36]
 [ 81]
 [126]]
h: [[ 42]
 [ 96]
 [150]]


In [ ]:
i = np.concatenate([f,g,h], axis=1) # 열로 합친다
print(i)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


[ 행렬식 ]

In [55]:
# 행렬식 : det
a = np.array([[3,1],[2,2]])
np.linalg.det(a)

4.000000000000001

In [ ]:
# 행렬 a의 행렬식이 4.0과 거의 같은지를 확인
np.allclose(4.0, np.linalg.det(a))

True

In [59]:
b = np.array([[3,1,3],[2,2,3],[1,1,1]])
print(b)

[[3 1 3]
 [2 2 3]
 [1 1 1]]


In [60]:
3 *np.linalg.det(b[1:,1:])

-3.0

In [ ]:
# b 배열에서 첫 번째 행을 제외하고, 짝수 번째 열만 선택한 부분 행렬
np.linalg.det(b[1:,::2])

0.0

In [63]:
3 * np.linalg.det(b[1:,:2])

0.0

In [64]:
np.linalg.det(b)

-2.0

In [65]:
a = np.array([[3,2],[6,4]])
np.linalg.det(a)

0.0

In [66]:
b = np.array([[1,2,3],[4,5,6],[3,2,4]])
np.linalg.det(b)

-9.000000000000002

In [ ]:
# 역행렬 함수 : inv
bi = np.linalg.inv(b)
bb = np.dot(b, bi)
# np.eye(3) : 3X3인 단위행렬
np.allclose(np.eye(3),bb)

True

In [69]:
# 특정 행렬이 역행렬이 없을 때네는 역행렬을 임의로 계산하는 것 : 의사 역행렬
a = np.ones([3,3])
print(np.linalg.det(a))
print(np.linalg.pinv(a))

0.0
[[0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]]


In [70]:
try:
    np.linalg.inv(a)
except Exception as e:
    print(e)

Singular matrix


In [72]:
# 전치행렬
# 아이슈타인의 합은 선형대수락을 물리학에 응용하면서 좌표계에 관한 공식을 다룰 때
# 유용한 표기 규칙으로 선형대수를 편리하게 계산할수 있는 방법
A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [75]:
# Einsum으로 벡터의 원소를 합친 경우는 하나의 인덱스를 표시하고 결과는 아무것도 표기사지 않음
# 벡터는 하나, 행렬은 두개의 인덱스 문자로 사용해야함
AA = np.arange(10)
np.einsum('i->',AA)
np.sum(AA)

45

In [ ]:
A__ = np.array([[1,1,1],[3,2,4],[7,5,8]])
np.einsum("ij->",A__)

32

In [ ]:
# 행축으로 더해짐
print(np.einsum("ij->i",A__))
print(np.sum(A__, axis=1))

# 열축으로 더해짐
print(np.einsum("ij->j",A__))
print(np.sum(A__, axis=0))

[ 3  9 20]
[ 3  9 20]
[11  8 13]
[11  8 13]


In [87]:
# 두개 배열의 연산
C = np.arange(10)
D = np.arange(5, 15)
print(C)
print(D)

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]


In [89]:
# 두 벡터의 곱셈
print(np.einsum('i,i->i',C, D))

# 두 벡터의 닷 연산
print(np.einsum('i,i->', C, D))
print(np.dot(C,D))

[  0   6  14  24  36  50  66  84 104 126]
510
510


In [90]:
# 행렬 einsum 연산
E = np.arange(10).reshape(2,5)
F = np.arange(5,15).reshape(2,5)
print(E)
print(F)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[ 5  6  7  8  9]
 [10 11 12 13 14]]


In [91]:
np.einsum("ij,ij->ij",E, F)

array([[  0,   6,  14,  24,  36],
       [ 50,  66,  84, 104, 126]])

In [93]:
# 행렬의 닷연산
print(np.einsum("ij,jk->ik",E, F.T))
print(np.dot(E, F.T))

[[ 80 130]
 [255 430]]
[[ 80 130]
 [255 430]]


[ 5. 다차원 배열의 구조 변경하기 ]

In [94]:
# 배열의 형상 변경
# 1차원 배열을 만들고 내부의 원소 개수가 동일한 형상을 가진 다른 차원의 배열을 변경할 수 있음
# Reshape 메소드에 형상을 인자로 전달해서 배열의 형상을 변경
x = np.arange(16)
print(x)

x1 = x.reshape(2,8)
print(x1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


In [95]:
# 원고의 개수가 안 맞으면 에러 발생
try:
    x2 = x.reshape(4,5)
except Exception as e:
    print(e)

cannot reshape array of size 16 into shape (4,5)


In [96]:
# -1을 지정하면 나머지 형상을 자동으로 세팅됨
y1 = x.reshape(4,-1)
y1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
# 배열의 크기 변경 (resize)
# reshape와 차이점은 더 큰 배열로 확장할 수 있음
# 동일 차원에서 크기만 확장
a = np.arange(4)
a

array([0, 1, 2, 3])

In [98]:
np.resize(a,8)

array([0, 1, 2, 3, 0, 1, 2, 3])

In [100]:
np.append(a,a)

array([0, 1, 2, 3, 0, 1, 2, 3])

In [101]:
# shape를 다른 차원으로 확대 기능
b = np.arange(4)
b.resize((4,4))
b

array([[0, 1, 2, 3],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [104]:
# 새로운 배열을 만들때, refcheck=False 지정
c = np.arange(8)
c.resize(4, refcheck=False)
c

array([0, 1, 2, 3])

In [106]:
# 1차원 배열을 2차원 배열로 변경
x = np.arange(3)
y = np.arange(4)

x__,y__ = np.meshgrid(x,y)

In [107]:
print(x__)
print(y__)

[[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]]
[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]]


In [108]:
x_1 = x.reshape(1,-1)

In [110]:
np.concatenate([x_1, x_1, x_1,x_1])

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [111]:
y_1 = y.reshape(-1,1)
np.concatenate([y_1,y_1,y_1,y_1], axis=1)

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

In [ ]:
# 1차원 배열을 2차원 배열로 변경2
# mgrid함수에 인자로 슬라이스 전달하면 두개의 배결을 반환
np.arange(10,30,10)

array([10, 20])

In [113]:
np.arange(1,5)

array([1, 2, 3, 4])

In [114]:
np.broadcast_arrays(np.arange(10,30,10).reshape(2,1),
                    np.arange(1,5).reshape(1,4))

[array([[10, 10, 10, 10],
        [20, 20, 20, 20]]),
 array([[1, 2, 3, 4],
        [1, 2, 3, 4]])]

In [117]:
a, b = np.mgrid[10:30:10, 1:5]
print(a)
print(b)

[[10 10 10 10]
 [20 20 20 20]]
[[1 2 3 4]
 [1 2 3 4]]


In [119]:
# 1차원 배열을 2차원 배열로 변경3
# Ogrid함수에 인자로 슬라이스 전달하면 2차원 두개의 배열을 반환
# 첫번때 열벡터이고 두번쨰는 행벡터임
# 이 두개를 브로드캐스팅해서 동인한 형상의 매열을 만들 수 있음
c,d = np.ogrid[10:30:10, 1:5]
print(c)
print(d)

[[10]
 [20]]
[[1 2 3 4]]


In [120]:
# 축이 1인 차원을 줄이기
x = np.array([[[0], [1], [2]]])
print(x)

[[[0]
  [1]
  [2]]]


In [121]:
x.shape

(1, 3, 1)

In [122]:
np.squeeze(x)

array([0, 1, 2])

In [125]:
print(np.squeeze(x, axis=0))
print(np.squeeze(x, axis=0).shape)

[[0]
 [1]
 [2]]
(3, 1)


In [126]:
print(np.squeeze(x, axis=2))
print(np.squeeze(x, axis=2).shape)

[[0 1 2]]
(1, 3)


In [128]:
# 내부 원소를 가지고 배열 확대하기
# 원소를 반복해서 증가하는 repeat 함수, 주어진 배열의 크기를 확대하는
# tile함수
a = np.linspace(1,5,5, dtype=np.int32)
print(a)
print(np.repeat(a,2))

[1 2 3 4 5]
[1 1 2 2 3 3 4 4 5 5]


In [ ]:
e = np.arange(4).reshape(2,2)
print(e)
print(np.tile(e,2))

[[0 1]
 [2 3]]
[[0 1 0 1]
 [2 3 2 3]]


In [131]:
# 배열을 쌓기
# 두 개의 일차원 배열을 만들고 stack, vstack, hstack함수로
# 배열을 수직과 수평으로 쌓을 수 있음
x = np.array([1,2,3])
y = np.array([4,5,6])
np.stack([x,y])

array([[1, 2, 3],
       [4, 5, 6]])

In [135]:
print(np.stack([x,y],axis=0)) # 수평으로
a = np.vstack([x,y])
print(a)
print(np.vstack([a,a]))

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [ ]:
np.stack([x,y],axis=1) # 수직으로

array([[1, 4],
       [2, 5],
       [3, 6]])

In [136]:
b = np.hstack([x,y])
print(b)

[1 2 3 4 5 6]


In [137]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [ ]:
# 배열 쌓기 객체
# 행과 열을 쌓을 떄, r__, c__를 사용할 수 있음
a = np.arange(6).reshape(2,3)
c = np.random.randn(2,3)
np.r_[a,c] # r:row

array([[ 0.        ,  1.        ,  2.        ],
       [ 3.        ,  4.        ,  5.        ],
       [ 0.90842892, -0.28075815, -1.43285827],
       [ 1.2478039 , -0.50664321, -0.84952404]])

In [ ]:
np.c_[a,c] # c : cloumn

array([[ 0.        ,  1.        ,  2.        ,  0.90842892, -0.28075815,
        -1.43285827],
       [ 3.        ,  4.        ,  5.        ,  1.2478039 , -0.50664321,
        -0.84952404]])

[ 문자 자료형 ]

In [ ]:
# 문자 자료형 : 바이트 문자열
# 다차원 배열의 원소가 문자열일 경우, dtype='S'로 처리하면 문자열 앞에
# b가 붙어서 바이트 문자열로 처리됨 #
s = np.array([['a','b'], ['c','d']], dtype='S')
s

array([[b'a', b'b'],
       [b'c', b'd']], dtype='|S1')

In [143]:
s[0,0]

b'a'

In [145]:
# 문자 자료형 : 문자열
# 다차원 배열의 원소가 문자열일 경우, dtype='U', np.str_등으로 처리하면
# 일반적인 문자열로 처리
u1 = np.array([['a','b'], ['c','d']])
u2 = np.array([['a','b'], ['c','d']])

ss = np.dtype(np.str_)
b = np.array([['a','b'], ['c','d']], dtype=ss)
b

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

In [146]:
# 문자 자료형 처리
# 다차원 배열의 자료형은 파이썬 문자열을 처리하는 자료형 : object
# 다차원 배열을 만들 때 문자의 길이에 따라 문자열을 수정할 수 있음
a= np.array(['abc','12345'], dtype=object)
a

array(['abc', '12345'], dtype=object)

In [147]:
type(a[0])

str

In [148]:
b = np.array([b'abc',b'12345'], dtype=object)
b

array([b'abc', b'12345'], dtype=object)

In [149]:
type(b[0])

bytes

In [150]:
d5 = np.array(range(10), dtype='S5').reshape(2,5)
d5

array([[b'0', b'1', b'2', b'3', b'4'],
       [b'5', b'6', b'7', b'8', b'9']], dtype='|S5')

In [158]:
print(d5[0])

[b'0' b'1' b'2' b'3' b'4']


In [159]:
d5[0,0] = "Hello"
d5

array([[b'Hello', b'1', b'2', b'3', b'4'],
       [b'5', b'6', b'7', b'8', b'9']], dtype='|S5')

[ 로그 함수 ]

In [161]:
# 지수함수
# 자연상수 e를 기준으로 처리
np.exp(0)

1.0

In [162]:
np.exp(-2)

0.1353352832366127

In [164]:
1/np.exp(2)

0.1353352832366127

In [ ]:
# 지수함수 power(거듭제곱 4)
a = np.power(np.e,2)
a

7.3890560989306495

[ 통계 함수 ]

In [168]:
a = np.array([1,3,7,9])
print(np.max(a))
print(np.min(a))

9
1


In [169]:
b = np.random.randn(3,4)
b

array([[ 0.4035654 ,  0.55316072, -0.48066802,  1.44492733],
       [-3.57691557, -1.01184424, -1.70884884,  1.32224497],
       [ 0.08208555, -0.54112745, -0.23697698, -0.19315035]])

In [170]:
np.max(b,axis=0)

array([ 0.4035654 ,  0.55316072, -0.23697698,  1.44492733])

In [171]:
np.max(b,axis=1)

array([1.44492733, 1.32224497, 0.08208555])

In [175]:
c = np.array([[3,7,5], [8,4,3],[2,4,9]])
print(np.amin(c))
print(np.amin(c,0))
print(np.amin(c,1))

2
[2 4 3]
[3 3 2]


In [186]:
d = np.random.randn(3,4)
d

array([[ 0.73937252, -0.32709629,  0.21052495,  1.27028479],
       [ 0.63126717, -0.06978655, -0.1376128 ,  2.34732749],
       [ 0.5323091 ,  1.2005261 ,  0.74615276,  0.18904311]])

In [187]:
np.argmax(d)

7

In [ ]:
# 열 방향으로 최댓값의 인덱스 값을 출력해줌
np.argmax(d, axis=0) 

array([0, 2, 2, 1], dtype=int64)

In [189]:
np.argmin(d, axis=0)

array([2, 0, 1, 2], dtype=int64)

In [190]:
# 최댓값과 최솟값의 차이는 np.ptp
a = np.array([[3,7,5],[8,4,3],[2,4,9]])
np.ptp(a)

7

In [191]:
# 배열 내의 숫자들이 빈도 수에 따른 값을 추출할 필요가 있을 경우
# 이 수들을 백분율을 기준으로 처리할 수 있음
np.max(a,axis=0) - np.min(a,axis=0)

array([6, 3, 6])

In [192]:
np.ptp(a,axis=0)

array([6, 3, 6])

In [193]:
np.ptp(a, axis=1)

array([4, 5, 7])